name: color_quiz
description: Color Quiz

version: 1.0.0+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: 2.1.0
  cupertino_icons: ^0.1.2
  flutter_colorpicker: ^0.2.6
  sqflite: ^1.1.7+2
  path: ^1.6.4
  shared_preferences: ^0.5.6+3
  i18n_extension: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter:

  uses-material-design: true

  assets:
    - assets/colors/colors.csv

  fonts:
    - family: Quinngothic
      fonts:
        - asset: assets/fonts/Quinngothic-Wyy1O.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  # flutter pub run flutter_launcher_icons:main